defmodule Clay.Repo.Migrations.CreateList do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:lists, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
    end

    alter table(:books) do
      add :list_id,
          references(:lists,
            column: :id,
            name: "books_list_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create index(:books, [:list_id])
  end

  def down do
    drop_if_exists index(:books, [:list_id])

    drop constraint(:books, "books_list_id_fkey")

    alter table(:books) do
      remove :list_id
    end

    drop table(:lists)
  end
end
