defmodule Clay.Repo.Migrations.CreateBook do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:books, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :author, :text, null: false
      add :series, :text
      add :episode, :bigint
      add :title, :text, null: false
      add :read, :boolean, null: false, default: false
      add :rating, :bigint
    end
  end

  def down do
    drop table(:books)
  end
end
