defmodule Clay.Repo.Migrations.AddUserToListsAndBooks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:lists) do
      add :user_id,
          references(:users,
            column: :id,
            name: "lists_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    alter table(:books) do
      add :user_id,
          references(:users,
            column: :id,
            name: "books_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:books, "books_user_id_fkey")

    alter table(:books) do
      remove :user_id
    end

    drop constraint(:lists, "lists_user_id_fkey")

    alter table(:lists) do
      remove :user_id
    end
  end
end
